steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/zotero-mcp-server:$COMMIT_SHA', '.']

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/zotero-mcp-server:$COMMIT_SHA']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'climate-research-mcp-server'
      - '--image'
      - 'gcr.io/$PROJECT_ID/zotero-mcp-server:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'ZOTERO_API_KEY=XjwHbvJLJur6PkAYtTuptSBH,ZOTERO_USER_ID=13099156,ZOTERO_COLLECTION_KEY=3D2RKLK311,NODE_ENV=production,MCP_API_KEY=climate-index-research-2025'

images:
  - 'gcr.io/$PROJECT_ID/zotero-mcp-server:$COMMIT_SHA'