steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/zotero-mcp-server:$COMMIT_SHA', '.']

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/zotero-mcp-server:$COMMIT_SHA']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'zotero-mcp-server'
      - '--image'
      - 'gcr.io/$PROJECT_ID/zotero-mcp-server:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'ZOTERO_API_KEY=${_ZOTERO_API_KEY},ZOTERO_USER_ID=${_ZOTERO_USER_ID},ZOTERO_COLLECTION_KEY=${_ZOTERO_COLLECTION_KEY}'

# Available substitutions for environment variables
substitutions:
  _ZOTERO_API_KEY: ''
  _ZOTERO_USER_ID: ''
  _ZOTERO_COLLECTION_KEY: ''

images:
  - 'gcr.io/$PROJECT_ID/zotero-mcp-server:$COMMIT_SHA'